version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: repo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: repo_explainer
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: repo_redis
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama
    container_name: repo_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    entrypoint: >
      sh -c "
      ollama serve &
      sleep 10 &&
      ollama pull nomic-embed-text &&
      ollama pull llama3.2 &&
      wait
      "

  backend-api:
    build: 
      context: ./backend
    container_name: repo_backend_api
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - OLLAMA_BASE_URL=http://ollama:11434
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
      - ollama

  backend-worker:
    build: 
      context: ./backend
    container_name: repo_backend_worker
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - OLLAMA_BASE_URL=http://ollama:11434
    command: ["node", "dist/workers/ingestWorker.js"]
    depends_on:
      - postgres
      - redis
      - ollama
  
  backend-metrics-worker:
    build: 
      context: ./backend
    container_name: repo_backend_metrics_worker
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - OLLAMA_BASE_URL=http://ollama:11434
    command: ["node", "dist/workers/metricsWorker.js"]
    depends_on:
      - postgres
      - redis
      - ollama

volumes:
  pgdata:
  ollama: