version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: repo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: repo_explainer
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: repo_redis
    ports:
      - "6379:6379"

  backend-api:
    build: 
      context: ./backend
    container_name: repo_backend_api
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis

  backend-worker:
    build: 
      context: ./backend
    container_name: repo_backend_worker
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    command: ["node", "dist/workers/ingestWorker.js"]
    depends_on:
      - postgres
      - redis
  
  backend-metrics-worker:
    build: 
      context: ./backend
    container_name: repo_backend_metrics_worker
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    command: ["node", "dist/workers/metricsWorker.js"]
    depends_on:
      - postgres
      - redis

volumes:
  pgdata: